name: spike-sonar-cloud
 
on:
  push:
    branches:
      - main

env:
  project_name: 'spike-sonar-cloud'

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 2


      - name: Change version of python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10' 
      - name: Use env
        run: |
          ls -ltr
          git branch
          git diff HEAD^.. --stat --name-only
          ${{secrets.PRUEBA}}
          export ${{secrets.PRUEBA2}}
          echo $hola $hola2
          echo $hola3 $hola4
          echo "variable_path=$(git diff HEAD^.. --stat --name-only | grep README.md)" >> $GITHUB_ENV
          python settings.py
      - name: Conditional variable_path
        if: variable_path == '/home/runner/work/spike-sonar-cloud/spike-sonar-cloud'
        run: echo "Se modifico el arcivo $variable_path"
      - name: Create Actions and download gist
        run: |
          echo -e "pytest\nbehave\nddt\npandas" > requirements.txt
          echo "variable_path: $variable_path"
          pip install -r requirements.txt
          pwd
          ls
          mkdir .github/gist
          curl https://gist.githubusercontent.com/JohanWilliamSanchez/32faa6691a280e72de6a92d12803699b/raw/ >  .github/gist/action.yml
          ls .github/
          python --version
      - name: Lo que sea
        id: miresultado
        run: echo resultado
      - name: Imprimir miresultado
        run: echo {{ steps.miresultado.result}}
      - name: impriir github
        run: echo hola

      - name: Get composite run steps repository
        uses: actions/checkout@v2
        with:
          repository: STHEPHEN3S/envrinments-spike
          # Personal access token to check out private repository
          # token: ${{ secrets.ACCESTOKEN }}
          # Indicate where to check action out to
          # path: .github/myaction

      - name: Run action from private repo
        uses: ./.github/myaction
      - name: Run action from private repo 2
        uses: ./.github/myaction/other-local

