name: spike-sonar-cloud
 
on:
  push:
    branches:
      - main

env:
  project_name: 'spike-sonar-cloud'

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#       - name: SonarCloud Scan
#         uses: sonarsource/sonarcloud-github-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Create Actions and download gist
        run: |
          pwd
          ls
          mkdir .github/gist
          curl https://gist.githubusercontent.com/JohanWilliamSanchez/32faa6691a280e72de6a92d12803699b/raw/ >  .github/gist/action.yml
          ls .github/

      - name: Get composite run steps repository
        uses: actions/checkout@v2
        with:
          repository: STHEPHEN3S/envrinments-spike
          # Personal access token to check out private repository
          token: ${{ secrets.ACCESTOKEN }}
          # Indicate where to check action out to
          path: .github/myaction

      - name: Run action from private repo
        uses: ./.github/myaction
      - name: Run action from private repo 2
        uses: ./.github/myaction/other-local

